language: python
python:
  - '3.5'
install: pip install -r requirements.txt
script: make test
deploy:
  provider: heroku
  api_key:
    secure: QOmtkGm/ta0dxcG2hWFnQSgBW8JiH8alpSoiRF6KaZ0lJd0+QtujLbiHqvHE/BHBbuCdHtx+y9lkQdKfG+DDrZgdhMm1m+C9MJox2r573V9onNEJIRmHc2/Rg5qskRZMa0JArfV3Xn/pJz0LCBf0oS2I+VfNhgKvmkuW9zKhXVE=
  app:
    develop: soundslike-staging
  on:
    repo: soundslike/soundslike
services:
  - postgresql
before_script:
  - psql -c 'create database "soundslike-test";' -U postgres
env:
  - TEST_DATABASE_URL=postgresql://postgres@localhost:5432/soundslike-test
