"""add song_relations

Revision ID: 47591e8eb26
Revises: 24e14488095
Create Date: 2016-12-07 18:11:44.009770

"""

# revision identifiers, used by Alembic.
revision = '47591e8eb26'
down_revision = '24e14488095'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song1_id', sa.Integer(), nullable=True),
    sa.Column('song2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song1_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['song2_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song1_id', 'song2_id', name='uc_song_relation')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_relations')
    ### end Alembic commands ###
