"""add member_since col to users

Revision ID: 5499e052ef8
Revises: 708af0af87
Create Date: 2015-04-19 00:24:31.339352

"""

# revision identifiers, used by Alembic.
revision = '5499e052ef8'
down_revision = '708af0af87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    ### end Alembic commands ###
