"""add user_id col to song_relations

Revision ID: 8153b01666
Revises: 15ee4c5ad20
Create Date: 2017-03-11 00:46:50.797733

"""

# revision identifiers, used by Alembic.
revision = '8153b01666'
down_revision = '15ee4c5ad20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_relations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users', 'song_relations', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users', 'song_relations', type_='foreignkey')
    op.drop_column('song_relations', 'user_id')
    ### end Alembic commands ###
